language: r
dist: trusty
sudo: true
os:
- linux
cache:
  directories:
    - $HOME/R/Library
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_eff113f965ce_key -iv $encrypted_eff113f965ce_iv
  -in credentials.enc -out credentials -d
- source credentials
- source <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
- git clone --branch cache-master https://github.com/dynverse/travis_package_cacher.git
- cd travis_package_cacher
- cat cache.tar.gz.part-* > cache.tar.gz
- tar -zxvf cache.tar.gz
- rm cache.tar*
- mv * $HOME/R/Library/
install:
- set -e
- update_docker
- install_hdf5
- install_cran remotes
- install_github_withdeps dynverse/dynwrap dynverse/dyntoy
script:
- source version
- build_docker
- test_docker
after_success:
- push_docker
