language: r
dist: trusty
sudo: true
os:
- linux
cache:
  directories:
    - $HOME/R/Library
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_eff113f965ce_key -iv $encrypted_eff113f965ce_iv
  -in credentials.enc -out credentials -d
- source credentials
- source <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
- install_dynverse
install:
- set -e
- update_docker
- install_hdf5
- install_cran remotes
- install_github_withdeps dynverse/dynwrap dynverse/dyntoy
- wget https://raw.githubusercontent.com/rcannood/SCORPIUS/dynwrap/inst/dynwrap/example.sh
script:
- source version
- build_docker
- test_docker
after_success:
- push_docker
